# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
machine:
    environment:
      PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
orbs:
  aws-cli: circleci/aws-cli@0.1.13
defaults: &defaults
  docker:
    - image: cypress/base:10
      environment:
          ## this enables colors in the output
          TERM: xterm

jobs:
  build:
    <<: *defaults
    working_directory: ~/amplify-js
    resource_class: large
    steps:
      - checkout
      - run: yarn config set workspaces-experimental true
      - run: yarn
      - run: yarn run bootstrap
      - run: yarn run build
      - run: yarn run coverage

      - save_cache:
          key: amplify-ssh-deps-{{ .Branch }}
          paths:
            - ~/.ssh
      - persist_to_workspace:
          root: /root
          paths: amplify-js
  amplify_ui_tests:
    working_directory: ~/
    docker:
        - image: cypress/base:10
    steps:
      - attach_workspace:
          at: ./
      - run: 
          name: "Build amplify cli"
          command: |
            mkdir videos
            mkdir screenshots
            git clone -b integtest --single-branch https://github.com/AaronZyLee/amplify-cli.git
            cd amplify-cli
            yarn cache clean --force
            yarn
            yarn config set workspaces-experimental true
            yarn run production-build
      - run:
          name: "Install Cypress Binary"
          command: npm install --save-dev cypress
      - run:
          name: "Install AWS CLI dependencies"
          command: |
            apt-get install -y sudo
            sudo apt-get install -y lsof
            sudo apt-get install -y python
            sudo apt-get update && sudo apt-get install -y python-pip libpython-dev
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: "Link dependencies"
          command: |
            cd amplify-js/packages/aws-amplify
            yarn link
            cd ../aws-amplify-react
            yarn link
      - run:
          command: "cd amplify-cli/packages/amplify-ui-tests && yarn run ui js"
          name: "Run Amplify ui tests"
          no_output_timeout: 45m
      - store_artifacts:
          path: /root/videos
      - store_artifacts:
          path: /root/screenshots
  unit_test:
    <<: *defaults
    working_directory: ~/amplify-js
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: "Run Amplify JS unit tests"
          command: |
            yarn run test --scope @aws-amplify/auth
            yarn run test --scope @aws-amplify/api
            yarn run test --scope @aws-amplify/analytics
            yarn run test --scope @aws-amplify/cache
            yarn run test --scope @aws-amplify/core
            yarn run test --scope @aws-amplify/interactions
            yarn run test --scope @aws-amplify/pubsub
            yarn run test --scope @aws-amplify/predictions
            yarn run test --scope @aws-amplify/storage
            yarn run test --scope @aws-amplify/xr
            yarn run test --scope aws-amplify-react
            yarn run test --scope aws-amplify-angular
            yarn run test --scope aws-amplify-vue
  integration_test_setup:
    <<: *defaults
    working_directory: ~/
    steps:
      - run: 
          name: "Clone Amplify JS Samples repo, install cypress, install react samples authenticator and link amplify packages"
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            echo $SSH_HOST_PUBLIC_KEY >> ~/.ssh/known_hosts
            git clone $AMPLIFY_JS_SAMPLES_STAGING_URL
            cd amplify-js-samples-staging
            yarn
      - save_cache:
          key: amplify-js-{{ .Branch }}-{{ checksum "amplify-js-samples-staging/yarn.lock" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress
      - persist_to_workspace:
          root: /root
          paths: amplify-js-samples-staging
  integ_react_predictions:
    <<: *defaults
    working_directory: ~/
    steps:
      - attach_workspace:
          at: /root
      - restore_cache:
          key: amplify-js-{{ .Branch }}-{{ checksum "amplify-js-samples-staging/yarn.lock" }}
      - run:
          name: "Link aws-amplify"
          command: |
            cd amplify-js/packages/aws-amplify
            yarn link
      - run:
          name: "Link predictions"
          command: |
            cd amplify-js/packages/predictions
            yarn link
      - run:
          name: "Install Predictions React sample"
          command: |
            cd amplify-js-samples-staging/samples/react/predictions/multi-user-translation
            yarn
            yarn link aws-amplify
            yarn link @aws-amplify/predictions
      - run:
          name: "Start Predictions React Sample server in background"
          command: |
            cd amplify-js-samples-staging/samples/react/predictions/multi-user-translation
            yarn start
          background: true
      - run:
          name: "Run cypress tests for Predictions React Sample"
          command: |
            cd amplify-js-samples-staging
            yarn cypress:react --spec "cypress/integration/predictions/multiuser-translation.spec.js"
      - store_artifacts:
          path: amplify-js-samples-staging/cypress/videos
      - store_artifacts:
          path: amplify-js-samples-staging/cypress/screenshots
  integration_test_react:
    <<: *defaults
    working_directory: ~/
    steps:
      - attach_workspace:
          at: /root
      - restore_cache:
          key: amplify-js-{{ .Branch }}-{{ checksum "amplify-js-samples-staging/yarn.lock" }}
      - run:
          name: "Install React Authenticator sample"
          command: |
            cd amplify-js-samples-staging/samples/react/auth/with-authenticator
            yarn
      - run:
          name: "Link aws-amplify"
          command: |
            cd amplify-js/packages/aws-amplify
            yarn link
      - run:
          name: "Link aws-amplify-react"
          command: |
            cd amplify-js/packages/aws-amplify-react
            yarn link
      - run:
          name: "Install React Authenticator sample"
          command: |
            cd amplify-js-samples-staging/samples/react/auth/with-authenticator
            yarn
            yarn link aws-amplify
            yarn link aws-amplify-react
      - run:
          name: "Start React Authenticator Sample server in background"
          command: |
            cd amplify-js-samples-staging/samples/react/auth/with-authenticator
            yarn start
          background: true
      - run:
          name: "Run cypress tests for React Authenticator Sample"
          command: |
            cd amplify-js-samples-staging
            yarn cypress:react --spec "cypress/integration/auth/authenticator.spec.js"
      - store_artifacts:
          path: amplify-js-samples-staging/cypress/videos
      - store_artifacts:
          path: amplify-js-samples-staging/cypress/screenshots
  integration_test_vue:
    <<: *defaults
    working_directory: ~/
    steps:
      - attach_workspace:
          at: /root
      - restore_cache:
          key: amplify-js-{{ .Branch }}-{{ checksum "amplify-js-samples-staging/yarn.lock" }}
      - run:
          name: "Install Vue Authenticator sample"
          command: |
            cd amplify-js-samples-staging/samples/vue/auth/amplify-authenticator
            yarn
      - run:
          name: "Link aws-amplify"
          command: |
            cd amplify-js/packages/aws-amplify
            yarn link
      - run:
          name: "Link aws-amplify-vue"
          command: |
            cd amplify-js/packages/aws-amplify-vue
            yarn link
      - run:
          name: "Start Vue Authenticator Sample server in background"
          command: |
            cd amplify-js-samples-staging/samples/vue/auth/amplify-authenticator
            yarn start
          background: true
      - run:
          name: "Run cypress tests for Vue Authenticator Sample"
          command: |
            cd amplify-js-samples-staging
            yarn cypress:vue --spec "cypress/integration/auth/authenticator.spec.js"
      - store_artifacts:
          path: amplify-js-samples-staging/cypress/videos
      - store_artifacts:
          path: amplify-js-samples-staging/cypress/screenshots
  deploy:
    <<: *defaults
    working_directory: ~/amplify-js
    steps:
      - attach_workspace:
          at: /root
      - restore_cache:
          keys: 
            - amplify-ssh-deps-{{ .Branch }}
            - amplify-ssh-deps
      - run:
          name: "Publish to Amplify Package"
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              npm whoami
              git config --global user.email $GITHUB_EMAIL
              git config --global user.name $GITHUB_USER
              git status
              git --no-pager diff
              yarn run publish:$CIRCLE_BRANCH
            else
              echo "Skipping deploy."
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      # - unit_test:
      #     requires:
      #       - build
      # - integration_test_setup:
      #     filters:
      #       branches:
      #         only:
      #           - release
      #           - master
      #     requires:
      #       - build
      # - integ_react_predictions:
      #     filters:
      #       branches:
      #         only:
      #           - release
      #           - master
      #     requires:
      #       - integration_test_setup
      # - integration_test_react:
      #     filters:
      #       branches:
      #         only:
      #           - release
      #           - master
      #     requires:
      #       - integration_test_setup
      # - integration_test_vue:
      #     filters:
      #       branches:
      #         only:
      #           - release
      #           - master
      #     requires:
      #       - integration_test_setup
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - release
      #           - master
      #           - beta
      #     requires:
      #       - unit_test
      #       - integration_test_react
      #       - integration_test_vue
      - amplify_ui_tests:
          requires:
            - build
