# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
machine:
    environment:
      PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

orbs:
  aws-cli: circleci/aws-cli@0.1.13

defaults: &defaults
  docker:
    - image: cypress/base:10
      environment:
          ## this enables colors in the output
          TERM: xterm

jobs:
  amplify_ui_tests:
    working_directory: ~/repo
    docker:
        - image: cypress/base:10
    steps:
      - attach_workspace:
          at: ./
      - run: 
          name: "Build amplify cli"
          command: |
            git clone -b dev --single-branch https://github.com/AaronZyLee/amplify-cli.git
            cd amplify-cli
            yarn cache clean --force
            yarn
            yarn config set workspaces-experimental true
            yarn run production-build
      - run: apt-get install -y sudo
      - run: sudo apt-get install -y lsof
      - run: sudo apt-get install -y python
      - run: sudo apt-get update && sudo apt-get install -y python-pip libpython-dev
      - aws-cli/install
      - aws-cli/configure
      - run:
          command: "cd amplify-cli/packages/amplify-ui-tests && yarn run ui js/auth"
          name: "Run Amplify ui tests-1"
          no_output_timeout: 45m
      - run:
          command: "cd amplify-cli/packages/amplify-ui-tests && yarn run ui js/storage"
          name: "Run Amplify ui tests-2"
          no_output_timeout: 45m
      - run:
          command: "cd amplify-cli/packages/amplify-ui-tests && yarn run ui js/api"
          name: "Run Amplify ui tests-3"
          no_output_timeout: 45m

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - amplify_ui_tests:
          filters:
            branches:
              only:
                - aaron